version: '3.9'

services:
  db:
    # platform: linux/amd64
    image: mysql:8.0
    environment: # コンテナで利用する環境変数の定義
      # MySQLインスタンスに必須な値、rootアカウントに設定するためのパスワードを指定
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # イメージ作成時のデータベース名。
      # 指定することでMYSQL_USER, MYSQL_PASSWORDは、スーバーユーザ権限のアカウントになる
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: $TZ

    volumes:
      - ./db-store:/var/lib/mysql
      # - ./api/tmp/db:/var/lib/mysql/data
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "$DB_PORT:$DB_PORT_CONTAINER_SIDE"

  api:
    build:
      context: ./api  # build context の指定 Dockerfileがあると想定される場所
      # Dockerfile内の変数をオーバーライドするための引数を指定
      args:
        WORKDIR: $WORKDIR # WORKDIRという変数に$WORKDIRという環境変数の値を渡す
    # コンテナ内の環境変数を設定
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE # MySQLのデータベース名(環境変数から取得)
      MYSQL_USER: $MYSQL_USER # ユーザ名(環境変数から取得)
      MYSQL_PASSWORD: $MYSQL_PASSWORD # パスワード(環境変数から取得)
      DB_PORT_CONTAINER_SIDE: $DB_PORT_CONTAINER_SIDE # コンテナ側のDBのポート番号(環境変数から取得)
    # ファイル共有をするためのエンドポイント
    volumes:
      - ./api:/$WORKDIR # ホスト側パス:コンテナ側パス
    # 依存しているサービス名(dbコンテナの構築後にwebが派生)
    depends_on:
      - db
    # ホストマシンとコンテナ間でポートをマッピング
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    # コンテナが起動する時に実行されるコマンド
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" # 古いPIDファイルを削除してから、Railsサーバを起動


  front:
    build:
      context: ./front  # build context の指定 Dockerfile の場所
      args:
        WORKDIR: $WORKDIR
        FRONT_PORT_CONTAINER_SIDE: $FRONT_PORT_CONTAINER_SIDE
    command: npm run dev
    # command: sh -c "cd vue3_try && npm run dev"
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:$FRONT_PORT_CONTAINER_SIDE"
    depends_on:
      - api

# networks:
#   web_segment:
#     driver: bridge
#     ipam:
#       config:
#       - subnet: 172.180.0.0/24
